steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest || exit 0
    id: Pull

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest
      - .
      - -f
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}
    id: Push

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_DEPLOY_REGION}
      - --quiet
    id: Deploy

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: gen-lang-client-0120628619
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: europe-west1
  _SERVICE_NAME: quibapp
  _TRIGGER_ID: 8e1ad315-98ee-49aa-8eff-a4dab54f5e4f
