steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}:latest || exit 0
    id: Pull

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}:latest
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - --build-arg
      - VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}:latest
      - .
      - -f
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}
    id: Push

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_DEPLOY_REGION}
      - --quiet
    id: Deploy

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_REPO}/${_SERVICE_NAME}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: gen-lang-client-0120628619
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: europe-west1
  _SERVICE_NAME: quibapp
  _IMAGE_REPO: rajeshgonuguntla-quib-frontend-test
  _VITE_API_BASE_URL: https://quib-app-backend-944587700647.europe-west1.run.app
  _VITE_GOOGLE_CLIENT_ID: 944587700647-v4d2dqg9io3q3qbgjoif32g21bcifg9s.apps.googleusercontent.com
  _TRIGGER_ID: ec7bf7b3-9d1c-4ffd-b77b-a60bf3d01a05
